Introduce limits on the number of events allowed per command context
atc-net/atc-cosmos-eventstore pull request #40
Opened 2023-06-23 09:21 UTC by christianhelle

The changes here introduce hard limits to the number of events the system can accept per operation.

Each command operation will consist of at least 2 operations in a transactional batch, one for upserting the stream metadata and the other for adding events.

The following limitations are introduced:
- A maximum of 10 events per command context (CQRS)
- A maximum of 50 events per stream batch (Event Store)

**CosmosDb Transactional batch operation limitations**
Currently, there are two known limits:
- The Azure Cosmos DB request size limit constrains the size of the TransactionalBatch payload to not exceed 2 MB, and the maximum execution time is 5 seconds.
- There's a current limit of 100 operations per TransactionalBatch to ensure the performance is as expected and within SLAs.

This resolves #39

2023-06-23 09:23 UTC, christianhelle commented
@LarsSkovslund I wrote this last night and thought that we can use this as a starting point for implementation detail discussions

2023-06-30 06:14 UTC, LarsSkovslund requested changes
Please remember to also update the change log.

2023-07-03 07:06 UTC, christianhelle commented on src/Atc.Cosmos.EventStore/Events/EventLimitExceededException.cs
> +public class EventLimitExceededException : EventStoreException
Yeah, it should be enough to use [`ArgumentOutOfRangeException`](https://learn.microsoft.com/en-us/dotnet/api/system.argumentoutofrangeexception) so I'll do that. 

I originally thought that [`ArgumentOutOfRangeException`](https://learn.microsoft.com/en-us/dotnet/api/system.argumentoutofrangeexception) was specific for collection indexers so I just checked the docs and I can verify that it doesn't seem to be specific to indexers

2023-07-03 09:29 UTC, christianhelle commented on src/Atc.Cosmos.EventStore/Events/EventLimitExceededException.cs
> +public class EventLimitExceededException : EventStoreException
After diving into the code and looking at the docs for [choosing the right standard exception](https://learn.microsoft.com/en-us/dotnet/api/system.exception?view=net-7.0#Standard) I think it best to use [`InvalidOperationException`](https://learn.microsoft.com/en-us/dotnet/api/system.invalidoperationexception) instead. 

`ArgumentOutOfRangeException` is designed to be used for the **argument** passed in, asserting the value of the argument itself

2023-07-03 09:32 UTC, LarsSkovslund commented on src/Atc.Cosmos.EventStore/Events/EventLimitExceededException.cs
> +public class EventLimitExceededException : EventStoreException
agreed, please remember to update the `CHANGELOG.md`

2023-07-03 09:45 UTC, christianhelle commented on src/Atc.Cosmos.EventStore/Events/EventLimitExceededException.cs
> +public class EventLimitExceededException : EventStoreException
I updated the change log

2023-07-03 09:50 UTC, LarsSkovslund approved these changes

2023-07-03 10:00 UTC, LarsSkovslund approved these changes

2023-07-03 10:09 UTC, merged